# Generated by Django 5.0.6 on 2024-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_author_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
    ]
