# Generated by Django 5.0.6 on 2024-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_autor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
