# Generated by Django 5.0.6 on 2024-06-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_author_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='author',
            new_name='name',
        ),
    ]
